title: ADA-AGIX Bridge Info
email: agix-ada-bridge@singularitynet.io
description: "ADA-AGIX Bridge Information Portal "
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://info-bridge.singularitynet.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
#search_enabled: false
#footer_content: "Copyright &copy; Test <a href=\"#\">All Rights Reserved.</a>"
footer_content: "&copy; 2021 <a href='https://singularitynet.io/' target='_blank'>SingularityNET</a> All rights reserved."
logo: "/assets/images/snet.png"
nav_sort: case_insensitive

# Build settings
theme: "just-the-docs"
sass:
    sass_dir: ./just-the-docs/_sass
    style: compressed
layouts_dir: ./just-the-docs/_layouts
includes_dir: ./just-the-docs/_includes
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
